export const SUPABASE_URL = "https://ldomjfqgtzdfnbadswdj.supabase.co";
export const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkb21qZnFndHpkZm5iYWRzd2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5NDYzMDMsImV4cCI6MjA5NzUyMjMwM30.FGr42AUiWmYQWcFJuqyuAT30O9PbxC5mPelF2B2iwWA";
